"use client";

import InfoTip from "@/components/InfoTip";
import { EventItem } from "@/lib/hooks";

function formatWhen(e: EventItem) {
  const raw = e.ts || e.created_at;
  if (!raw) return "";
  const d = typeof raw === "number" ? new Date(raw * 1000) : new Date(raw);
  return Number.isNaN(d.getTime()) ? String(raw) : d.toLocaleString();
}

export default function EventsList({ items }: { items: EventItem[] }) {
  return (
    <div style={{ border: "1px solid #eee", borderRadius: 16, overflow: "hidden" }}>
      <div style={{ padding: 12, borderBottom: "1px solid #eee", fontWeight: 800 }}>
        Latest events
      </div>

      {items.length === 0 ? (
        <div style={{ padding: 16, color: "#555" }}>No events yet.</div>
      ) : (
        items.map((e, idx) => (
          <div
            key={e.id ?? `${e.type}-${idx}`}
            style={{
              padding: 12,
              borderBottom: idx === items.length - 1 ? "none" : "1px solid #f0f0f0",
              display: "flex",
              justifyContent: "space-between",
              gap: 12,
            }}
          >
            {/* LEFT */}
            <div style={{ minWidth: 0 }}>
              {/* TYPE */}
              <div style={{ fontWeight: 800 }}>
                {e.type === "duplicate"
                  ? "Duplicate blocked"
                  : e.type === "over_limit"
                  ? "Limit reached"
                  : e.type}
              </div>

              {/* DETAILS */}
              <div
                style={{
                  fontSize: 13,
                  color: "#555",
                  marginTop: 6,
                  display: "flex",
                  gap: 10,
                  flexWrap: "wrap",
                }}
              >
                {e.key ? (
                  <InfoTip
                    label={`key=${e.key}`}
                    description="Deduplication (idempotency) key. If the same key is received again within the lock window, the request is blocked to prevent duplicate execution."
                  />
                ) : null}

                {e.req_id ? (
                  <InfoTip
                    label={`req_id=${e.req_id}`}
                    description="Unique request ID generated by OnceOnly. Use it to locate this request in logs or when contacting support."
                  />
                ) : null}

                {e.first_seen_at ? (
                  <span style={{ color: "#777" }}>
                    first seen: {e.first_seen_at}
                  </span>
                ) : null}

                {e.plan && e.usage != null && e.limit != null ? (
                  <span style={{ color: "#777" }}>
                    plan: {e.plan} • usage: {e.usage}/{e.limit}
                  </span>
                ) : null}
              </div>
            </div>

            {/* RIGHT */}
            <div
              style={{
                whiteSpace: "nowrap",
                fontSize: 13,
                color: "#666",
                alignSelf: "flex-start",
              }}
            >
              {formatWhen(e)}
            </div>
          </div>
        ))
      )}
    </div>
  );
}
